name: CI

on: [push, pull_request]

jobs:

  test-valgrind:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
      - name: prep
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "GITHUB_REPOSITORY=${{github.event.inputs.use_repo}}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{github.event.inputs.use_git_ref}}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}
      - name: make
        run: make valgrind REDIS_CFLAGS='-Werror -DREDIS_TEST'
      - name: testprep
        run: |
          sudo apt-get update
          sudo apt-get install tcl8.6 tclx valgrind -y
      - name: module api test
        if: true && !contains(github.event.inputs.skiptests, 'modules')
        run: ./runtest-moduleapi --loop --stop --valgrind --no-latency --verbose --clients 1 --dump-logs ${{github.event.inputs.test_args}}

  test-macos-latest:
    runs-on: macos-latest
    timeout-minutes: 14400
    steps:
      - name: prep
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "GITHUB_REPOSITORY=${{github.event.inputs.use_repo}}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{github.event.inputs.use_git_ref}}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}
      - name: make
        run: make
      - name: test
        if: true && !contains(github.event.inputs.skiptests, 'redis')
        run: ./runtest --accurate --verbose --single integration/replication --loop --stop --no-latency --dump-logs ${{github.event.inputs.test_args}}
      - name: module api test
        if: true && !contains(github.event.inputs.skiptests, 'modules')
        run: ./runtest-moduleapi --verbose --dump-logs ${{github.event.inputs.test_args}}
